name: translationApp-Symfony
services:
  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../app:/var/www
    links:
      - php
  php:
    container_name: php
    build: php
    working_dir: /var/www
    volumes:
      - ../app:/var/www
  db:
    container_name: db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: devpass
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
