# Image and version
FROM php:8-fpm

RUN apt-get update
RUN apt install -y zip
RUN apt install -y git


# Call PHP images script `docker-php-ext-install` and install language extensions
RUN docker-php-ext-install pdo mysqli pdo_mysql

# copy the Composer PHAR from the Composer image into the PHP image
COPY --from=composer /usr/bin/composer /usr/bin/composer

# Install xdebug
RUN pecl install xdebug && docker-php-ext-enable xdebug

COPY php.ini /usr/local/etc/php/